### PR TITLE
add lua port

### PR DESCRIPTION
**Pull request by rangercyh**

### CODE REVIEW

**Comment by avaneev** [comment]
Thanks for the PR, but I do not plan to accept PRs for Komihash, let it be plain C. I can add a reference to your Lua implementation - let me know the URL.

**Comment by rangercyh** [comment]
Oh, my code is just a port for lua, no change to komihash c code. Maybe you can add my lua port URL : https://github.com/rangercyh/lua-komihash

**Comment by avaneev** [comment]
I've added a link to your LUA port. Also consider using `shift-right 11` operation over result, if LUA's float is Double type, for PRNG. This is important as to not induce any bias.

**Comment by rangercyh** [comment]
great idea, I will try to check it out

**Pull request closed without merging**
