### PR TITLE
added link to Java port

### PR DESCRIPTION
**Pull request by oertl**

### CODE REVIEW

**Comment by avaneev** [comment]
Thanks, I've added a link to your port, without using PR as I've added some formatting.

**Comment by avaneev** [comment]
I'll add that you should have left the original copyright intact. Translating to Java does not mean it's a new code by Dynatrace.

**Comment by oertl** [comment]
Hi Aleksey,

you are right, would it suit you, if I would put the original license in
combination with the Apache 2.0 license into the file Komihash4_3.java?
Komihash4_3.java includes more than just the original Komihash algorithm.
There is a lot of specialized code for hashing Java objects in a streaming
fashion.

Best regards

Otmar

**Comment by avaneev** [comment]
If you can, simply add "komihash 4.3 Copyright 2021 Aleksey Vaneev", I'm not claiming any other code, of course. But the "komihash" part should be covered by a copyright notice. MIT and Apache2 licenses are largely compatible except that Apache2 license better suits collaborative projects. I do not see a problem including MIT project into Apache2 project.

**Comment by oertl** [comment]
@avaneev, please check https://github.com/dynatrace-oss/hash4j/commit/c440d2a3e09ff698d8410e01aa6700ea298e2d59

**Comment by avaneev** [comment]
Thank you very much!

**Pull request closed without merging**
